package com.shopme.common.entity;

public enum EmailSetting {
    MAIL_HOST, MAIL_PORT, MAIL_USERNAME, MAIL_PASSWORD, SMTP_AUTH, SMTP_SECURED,
    MAIL_FROM, MAIL_SENDER_NAME, CUSTOMER_VERIFY_SUBJECT, CUSTOMER_VERIFY_CONTENT;

}
